### ISSUE TITLE
skimdb.iriscouch.com is gone now

### ISSUE THREAD

**Issue by nolanlawson** [calvinmetcalf/name-me#3]
IrisCouch shut me down. Feel free to use my new Cloudant mirror: http://nolan.cloudant.com/skimdb-mirror

**Comment by calvinmetcalf** [comment]
thanks

**Comment by calvinmetcalf** [comment]
you need to enable reader and replicator permissions on the db first, I tried to set my own up but cloudant wouldn't let me set the cors headers

**Comment by calvinmetcalf** [comment]
figured out how to turn on cors for my db, thanks though!

**Comment by nolanlawson** [comment]
Sorry about that, yeah, I forgot to set up the right CORS permissions for you. Glad it's working now!
